// src/pages/franchisePanel/Dashboard.jsx
import React, { useEffect, useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import api from "../../api/axiosConfig";
import { useStore } from "../../store";

/**
 * Franchise Dashboard
 *
 * - Shows KPIs: Total Sales, Today Sales, Pending Orders, Wallet (franchise)
 * - Shows PV/BV generated by franchise sales
 * - Recent orders list & quick actions (Create Order, Products, EPINs)
 * - Uses backend endpoints:
 *    GET  /franchise/dashboard      -> { totalSales, todaySales, pendingOrders, wallet, totalPV, totalBV }
 *    GET  /franchise/orders?limit=.. -> [{ id, customer, total, status, createdAt, pv, bv }]
 *    GET  /franchise/products       -> [{ id, name, price, pv, bv }]
 *
 * If your backend routes differ, change the api.* calls accordingly.
 */

export default function FranchiseDashboard() {
  const { state, actions } = useStore();
  const navigate = useNavigate();

  const [kpi, setKpi] = useState({
    totalSales: 0,
    todaySales: 0,
    pendingOrders: 0,
    wallet: 0,
    totalPV: 0,
    totalBV: 0,
  });
  const [orders, setOrders] = useState([]);
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [loadingOrders, setLoadingOrders] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    loadAll();
    // eslint-disable-next-line
  }, []);

  async function loadAll() {
    setLoading(true);
    setError(null);
    try {
      await Promise.all([fetchDashboard(), fetchOrders(), fetchProducts()]);
    } catch (err) {
      setError(err?.message || "Failed to load franchise dashboard");
      actions.addNotification({ type: "error", message: err?.message || "Failed to load franchise dashboard" });
    } finally {
      setLoading(false);
    }
  }

  async function fetchDashboard() {
    try {
      const res = await api.get("/franchise/dashboard");
      const data = res.data || res;
      setKpi({
        totalSales: data.totalSales ?? 0,
        todaySales: data.todaySales ?? 0,
        pendingOrders: data.pendingOrders ?? 0,
        wallet: data.wallet ?? 0,
        totalPV: data.totalPV ?? 0,
        totalBV: data.totalBV ?? 0,
      });
    } catch (err) {
      throw err;
    }
  }

  async function fetchOrders(limit = 8) {
    setLoadingOrders(true);
    try {
      const res = await api.get("/franchise/orders", { params: { limit } });
      const data = res.data || res;
      setOrders(Array.isArray(data) ? data : data.orders || []);
    } catch (err) {
      setOrders([]);
      throw err;
    } finally {
      setLoadingOrders(false);
    }
  }

  async function fetchProducts() {
    try {
      const res = await api.get("/franchise/products");
      const data = res.data || res;
      setProducts(Array.isArray(data) ? data : data.products || []);
    } catch (err) {
      setProducts([]);
      // non-fatal
    }
  }

  function fmt(v) {
    return `₹${Number(v || 0).toLocaleString("en-IN")}`;
  }

  return (
    <div className="p-6 pt-24">
      <div className="max-w-7xl mx-auto space-y-6">
        <header className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-semibold">Franchise Dashboard</h1>
            <p className="text-sm text-gray-500">Overview of your franchise sales, orders and PV/BV performance.</p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={() => navigate("/franchise/create-order")}
              className="px-3 py-2 bg-indigo-600 text-white rounded hover:bg-indigo-700 text-sm"
            >
              + Create Order
            </button>

            <Link to="/franchise/products" className="px-3 py-2 border rounded text-sm">
              Manage Products
            </Link>

            <Link to="/franchise/epins" className="px-3 py-2 border rounded text-sm">
              EPINs
            </Link>
          </div>
        </header>

        {error && <div className="text-sm text-red-600">{error}</div>}

        {/* KPI Row */}
        <div className="grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-6 gap-4">
          <div className="bg-white p-4 rounded shadow">
            <div className="text-xs text-gray-500">Total Sales</div>
            <div className="text-xl font-semibold mt-1">{fmt(kpi.totalSales)}</div>
            <div className="text-xs text-gray-400 mt-1">All-time</div>
          </div>

          <div className="bg-white p-4 rounded shadow">
            <div className="text-xs text-gray-500">Today Sales</div>
            <div className="text-xl font-semibold mt-1">{fmt(kpi.todaySales)}</div>
            <div className="text-xs text-gray-400 mt-1">Today</div>
          </div>

          <div className="bg-white p-4 rounded shadow">
            <div className="text-xs text-gray-500">Pending Orders</div>
            <div className="text-xl font-semibold mt-1">{kpi.pendingOrders}</div>
            <div className="text-xs text-gray-400 mt-1">Needs action</div>
          </div>

          <div className="bg-white p-4 rounded shadow">
            <div className="text-xs text-gray-500">Franchise Wallet</div>
            <div className="text-xl font-semibold mt-1">{fmt(kpi.wallet)}</div>
            <div className="text-xs text-gray-400 mt-1">Available</div>
          </div>

          <div className="bg-white p-4 rounded shadow">
            <div className="text-xs text-gray-500">Total PV</div>
            <div className="text-xl font-semibold mt-1">{kpi.totalPV}</div>
            <div className="text-xs text-gray-400 mt-1">Generated</div>
          </div>

          <div className="bg-white p-4 rounded shadow">
            <div className="text-xs text-gray-500">Total BV</div>
            <div className="text-xl font-semibold mt-1">{kpi.totalBV}</div>
            <div className="text-xs text-gray-400 mt-1">Generated</div>
          </div>
        </div>

        {/* Charts + Products */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          <div className="lg:col-span-2 bg-white p-4 rounded shadow">
            <div className="flex items-center justify-between mb-3">
              <h3 className="font-semibold">Recent Orders</h3>
              <div className="text-sm text-gray-500">{loadingOrders ? "Loading..." : `${orders.length} shown`}</div>
            </div>

            {orders.length === 0 ? (
              <div className="p-6 text-sm text-gray-500">No orders found. Create your first order.</div>
            ) : (
              <div className="overflow-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b">
                      <th className="py-2 text-left">Order ID</th>
                      <th className="py-2 text-left">Customer</th>
                      <th className="py-2 text-right">Total</th>
                      <th className="py-2 text-right">PV / BV</th>
                      <th className="py-2 text-left">Status</th>
                      <th className="py-2 text-left">Date</th>
                    </tr>
                  </thead>
                  <tbody>
                    {orders.map((o) => (
                      <tr key={o.id} className="border-b hover:bg-gray-50">
                        <td className="py-2">{o.id}</td>
                        <td className="py-2">{o.customer?.name || o.customer?.phone || "-"}</td>
                        <td className="py-2 text-right">{fmt(o.total)}</td>
                        <td className="py-2 text-right">{(o.pv || 0) + " / " + (o.bv || 0)}</td>
                        <td className="py-2">
                          <span
                            className={`px-2 py-1 rounded text-xs ${
                              o.status === "pending" ? "bg-yellow-100 text-yellow-800" : o.status === "delivered" ? "bg-green-100 text-green-800" : "bg-gray-100 text-gray-700"
                            }`}
                          >
                            {o.status}
                          </span>
                        </td>
                        <td className="py-2 text-xs text-gray-500">{new Date(o.createdAt).toLocaleString()}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            <div className="mt-3 flex justify-end">
              <button onClick={() => navigate("/franchise/orders")} className="px-3 py-2 border rounded text-sm">
                View All Orders
              </button>
            </div>
          </div>

          <div className="bg-white p-4 rounded shadow">
            <h3 className="font-semibold mb-3">Top Products</h3>

            {products.length === 0 ? (
              <div className="text-sm text-gray-500">No products configured yet.</div>
            ) : (
              <ul className="space-y-2">
                {products.slice(0, 6).map((p) => (
                  <li key={p.id} className="flex items-center justify-between border rounded p-2">
                    <div>
                      <div className="font-medium">{p.name}</div>
                      <div className="text-xs text-gray-500">PV: {p.pv ?? 0} • BV: {p.bv ?? 0}</div>
                    </div>
                    <div className="text-sm font-semibold">₹{p.price}</div>
                  </li>
                ))}
              </ul>
            )}

            <div className="mt-4">
              <button onClick={() => navigate("/franchise/create-order")} className="w-full px-3 py-2 bg-indigo-600 text-white rounded">
                Create Order
              </button>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="bg-white p-4 rounded shadow">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div className="text-sm text-gray-600">
              Use the franchise panel to place orders, generate EPINs and manage inventory. All PV/BV is computed server-side.
            </div>

            <div className="flex gap-2">
              <button onClick={() => loadAll()} className="px-3 py-2 border rounded text-sm">Refresh</button>
              <button onClick={() => navigate("/franchise/sales-report")} className="px-3 py-2 bg-green-600 text-white rounded text-sm">Sales Report</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
